//! Agentic Loop — autonomous multi-step task execution.
//!
//! Phase 5: agent receives a goal → plans steps → executes → verifies → reports.
//! No human intervention needed between steps.

use crate::provider::ProviderRegistry;
use crate::provider::{ChatCompletionRequest, ChatMessage};
use crate::tools::ToolRegistry;
use serde::{Deserialize, Serialize};
use std::sync::Arc;
use tokio::sync::RwLock;

/// Progress of an agentic task
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum TaskStatus {
    Planning,
    Executing { step: usize, total: usize },
    Verifying,
    Completed,
    Failed { reason: String },
}

impl std::fmt::Display for TaskStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            TaskStatus::Planning => write!(f, "🧠 Planning"),
            TaskStatus::Executing { step, total } => write!(f, "🔧 Step {}/{}", step, total),
            TaskStatus::Verifying => write!(f, "🔍 Verifying"),
            TaskStatus::Completed => write!(f, "✅ Completed"),
            TaskStatus::Failed { reason } => write!(f, "❌ Failed: {}", reason),
        }
    }
}

/// A single step in the plan
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlanStep {
    pub order: usize,
    pub tool_name: String,
    pub action: String,
    pub params: serde_json::Value,
    pub reason: String,
}

/// The full plan generated by LLM
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExecutionPlan {
    pub goal: String,
    pub steps: Vec<PlanStep>,
    pub success_criteria: String,
}

/// Result of the full agentic run
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgenticResult {
    pub goal: String,
    pub status: TaskStatus,
    pub plan: Vec<PlanStep>,
    pub results: Vec<String>,
    pub summary: String,
    pub duration_secs: f64,
    pub steps_completed: usize,
    pub steps_failed: usize,
}

pub struct AgenticEngine;

impl AgenticEngine {
    /// Generate a plan via LLM from a user's goal
    async fn plan(
        goal: &str,
        registry: &Arc<RwLock<ProviderRegistry>>,
        tools: &ToolRegistry,
    ) -> Option<ExecutionPlan> {
        let schemas = tools.schemas();
        let tool_list: Vec<String> = schemas
            .iter()
            .map(|s| format!("- {}: {} (params: {})", s.name, s.description, s.parameters))
            .collect();

        let prompt = format!(
            r#"You are an autonomous OS agent. Plan the steps to achieve the user's goal.

GOAL: {}

Available tools:
{}

Respond with ONLY a JSON object (no markdown, no explanation):
{{
  "goal": "original goal",
  "success_criteria": "how to know when done",
  "steps": [
    {{
      "order": 1,
      "tool_name": "package|process|service|filesystem|network",
      "action": "search|install|list|status|disk_usage|...",
      "params": {{"action": "...", "package": "..."}},
      "reason": "why this step"
    }}
  ]
}}

Rules:
- Max 5 steps
- Start with read-only checks first
- Each step must use ONE tool
- Only use tools from the list above
- Include success_criteria for when to stop
"#,
            goal,
            tool_list.join("\n")
        );

        let messages = vec![
            ChatMessage {
                role: "system".into(),
                content: "You are a task planner. Output only valid JSON. No markdown.".into(),
                tool_calls: None,
                tool_call_id: None,
            },
            ChatMessage {
                role: "user".into(),
                content: prompt,
                tool_calls: None,
                tool_call_id: None,
            },
        ];

        let req = ChatCompletionRequest {
            model: registry.read().await.active().model().to_string(),
            messages,
            temperature: Some(0.3),
            max_tokens: Some(1024),
            stream: None,
            tools: None,
        };

        match registry.read().await.active().chat(req).await {
            Ok(resp) => {
                let content = resp
                    .choices
                    .first()
                    .and_then(|c| c.message.content.clone())
                    .unwrap_or_default();
                // Try to extract JSON from markdown fences
                let json_str = if content.contains("```json") {
                    content
                        .split("```json")
                        .nth(1)
                        .and_then(|s| s.split("```").next())
                        .unwrap_or(&content)
                } else if content.contains("```") {
                    content
                        .split("```")
                        .nth(1)
                        .and_then(|s| s.split("```").next())
                        .unwrap_or(&content)
                } else {
                    &content
                };
                serde_json::from_str::<ExecutionPlan>(json_str.trim()).ok()
            }
            Err(e) => {
                tracing::error!("Plan generation failed: {}", e);
                None
            }
        }
    }

    /// Execute the full agentic loop
    pub async fn run(
        goal: &str,
        registry: &Arc<RwLock<ProviderRegistry>>,
        tools: &mut ToolRegistry,
        confirm_dangerous: bool,
        max_steps: usize,
    ) -> AgenticResult {
        let start = std::time::Instant::now();
        let mut results: Vec<String> = Vec::new();
        let mut completed = 0usize;
        let mut failed = 0usize;

        // Phase 1: Plan
        tracing::info!("Agentic: planning for '{}'", goal);
        let plan = match Self::plan(goal, registry, tools).await {
            Some(p) => p,
            None => {
                return AgenticResult {
                    goal: goal.to_string(),
                    status: TaskStatus::Failed {
                        reason: "LLM plan generation failed".into(),
                    },
                    plan: vec![],
                    results,
                    summary: "Could not generate a plan. Try a more specific goal.".into(),
                    duration_secs: start.elapsed().as_secs_f64(),
                    steps_completed: 0,
                    steps_failed: 1,
                };
            }
        };

        tracing::info!("Agentic: planned {} steps for '{}'", plan.steps.len(), goal);

        // Phase 2: Execute step by step
        let total_steps = plan.steps.len().min(max_steps);
        for (i, step) in plan.steps.iter().enumerate().take(max_steps) {
            tracing::info!(
                "Agentic: step {}/{} — {} {}: {}",
                i + 1,
                total_steps,
                step.tool_name,
                step.action,
                step.reason
            );

            results.push(format!(
                "📋 Step {}/{}: {} → {} ({})",
                i + 1,
                total_steps,
                step.tool_name,
                step.action,
                step.reason
            ));

            // Execute the tool
            let tool_result = tools
                .execute(&step.tool_name, &step.params, confirm_dangerous)
                .await;

            if tool_result.success {
                results.push(format!("   ✅ {}", tool_result.output));
                completed += 1;

                // Phase 3: Self-verify important steps
                if step.action == "install" || step.action == "remove" {
                    // Verify by checking package info
                    if let Some(pkg) = step.params["package"].as_str() {
                        let verify = tools
                            .execute(
                                "package",
                                &serde_json::json!({"action": "info", "package": pkg}),
                                false,
                            )
                            .await;
                        results.push(format!(
                            "   🔍 Verify: {}",
                            if verify.success {
                                "✅ Confirmed"
                            } else {
                                "⚠️ Check failed"
                            }
                        ));
                    }
                }
            } else {
                let err = tool_result.error.unwrap_or_else(|| "unknown error".into());
                let needs_confirm = err.contains("Reply 'yes'")
                    || err.contains("Needs confirmation")
                    || err.contains("needs confirmation");

                if needs_confirm && confirm_dangerous {
                    // Retry with confirmation
                    let retry = tools.execute(&step.tool_name, &step.params, true).await;
                    if retry.success {
                        results.push(format!("   ✅ (auto-confirmed) {}", retry.output));
                        completed += 1;
                    } else {
                        results.push(format!("   ❌ {}", retry.error.unwrap_or_default()));
                        failed += 1;
                    }
                } else if needs_confirm {
                    results.push(
                        "   ⚠️ Skipped (needs confirmation, use '/auto confirm <goal>')"
                            .to_string(),
                    );
                    failed += 1;
                } else {
                    results.push(format!("   ❌ {}", err));
                    failed += 1;
                }
            }
        }

        // Phase 4: Summarize
        let status = if failed == 0 || completed > 0 {
            TaskStatus::Completed
        } else {
            TaskStatus::Failed {
                reason: format!("{} steps failed", failed),
            }
        };

        let summary = format!(
            "🎯 Goal: {}\n📊 Result: {}/{} steps completed ({} failed)\n⏱️ Time: {:.1}s\n\n{}",
            goal,
            completed,
            total_steps,
            failed,
            start.elapsed().as_secs_f64(),
            results.join("\n"),
        );

        AgenticResult {
            goal: goal.to_string(),
            status,
            plan: plan.steps,
            results,
            summary,
            duration_secs: start.elapsed().as_secs_f64(),
            steps_completed: completed,
            steps_failed: failed,
        }
    }
}
